# installing dependencies
FROM ruby:3.1.3 AS builder

WORKDIR /app
COPY api .

# Install bundler version specified in Gemfile.lock
RUN gem install bundler -v 2.4.6

# Install dependencies
RUN bundle install

# Stage 2: Final image for running the application
FROM ruby:3.1.3

WORKDIR /app

# Copy only the installed gems from the builder stage
COPY --from=builder /usr/local/bundle /usr/local/bundle

COPY --from=builder /app /app

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
