apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.sidekiq }}
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: {{ .Values.image.sidekiq }}
        env:
        - name: REDIS_URL
          value: 'redis://redis:6379/1'
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: SECRET_KEY_BASE
        command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
