apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}
  DB_USER: {{ .Values.secrets.DB_USER }}
  SECRET_KEY_BASE: {{ .Values.secrets.SECRET_KEY_BASE }}
