name: Build, Push, and Create Kind Cluster

on:
  push:
    branches:
      - master

jobs:
  create-kind-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.17.0"

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init -upgrade

      - name: Apply Terraform Configuration
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Verify cluster
        run: |
          kubectl get nodes
          kubectl cluster-info

      - name: Deploy Nginx StatefulSet
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: nginx
          spec:
            serviceName: "nginx"
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.21.6
                  ports:
                  - containerPort: 80
                    name: web
                  volumeMounts:
                  - name: nginx-storage
                    mountPath: /usr/share/nginx/html
            volumeClaimTemplates:
            - metadata:
                name: nginx-storage
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
          EOF
    
      - name: Verify Nginx StatefulSet
        run: |
            kubectl get statefulsets
            kubectl get pods
            kubectl describe statefulset nginx
