name: Provision Kind Cluster

on:
  push:
    branches:
      - master

jobs:
  provision-kind-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0 

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init -upgrade

      - name: Apply Terraform Configuration
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Verify Kind Cluster
        run: |
          kubectl get nodes
          kubectl cluster-info

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart
        run: |
          helm install video-uploader ./Helm_chart/video-uploader-0.1.0.tgz

      - name: Modify /etc/hosts
        run: |
          echo "127.0.0.1 video-app.local" | sudo tee -a /etc/hosts

      - name: Curl Test
        run: |
          sleep 30  
          curl http://video-app.local
