name: Provision Kind Cluster and deploy application

on:
  push:
    branches:
      - master

jobs:
  provision-kind-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0 

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init -upgrade

      - name: Apply Terraform Configuration
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Verify Kind Cluster
        run: |
          kubectl get nodes
          kubectl cluster-info

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      - name: Create Namespace
        run: |
          kubectl create namespace video-uploader || echo "Namespace video-uploader already exists"

      - name: Deploy Helm Chart
        run: |
          cd Helm_Chart
          helm install video-uploader .

      - name: Modify /etc/hosts
        run: |
          echo "127.0.0.1 video-app.local" | sudo tee -a /etc/hosts

      - name: Ingress check
        run: |
          kubectl get ing -n video-uploader

      - name: Curl Test
        run: |
          sleep 30  
          curl http://video-app.local
