name: Build, Push, and Create Kind Cluster

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Build and push API image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.rails \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/api:latest \
            --push .

      - name: Build and push Sidekiq image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.rails \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/sidekiq:latest \
            --push .

      - name: Build and push SPA image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.react \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/spa:latest \
            --push .

      - name: Build and push Nginx image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.nginx \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest \
            --push .

  create-kind-cluster:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Setup Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.17.0"

    - name: Create Kind config file
      run: |
        cat << EOF > kind-config.yaml
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
        - role: worker
        - role: worker
        EOF

    - name: Create Terraform configuration
      run: |
        cat << EOF > main.tf
        terraform {
          required_providers {
            kind = {
              source  = "tehcyx/kind"
              version = "0.2.1"
            }
          }
        }

        resource "kind_cluster" "default" {
          name = "test-cluster"
          kind_config {
            kind = "Cluster"
            api_version = "kind.x-k8s.io/v1alpha4"
            node {
              role = "control-plane"
            }
            node {
              role = "worker"
            }
            node {
              role = "worker"
            }
          }
        }
        EOF

    - name: Initialize Terraform
      run: terraform init -upgrade

    - name: Create Kind cluster with Terraform
      run: terraform apply -auto-approve

    - name: Verify cluster
      run: |
        kubectl get nodes
        kubectl cluster-info
